  ---
title: "ME analysis (Shih)"
date: "2025"
output:
  html_document: default

---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = TRUE,
                      message = FALSE,
                      warning = FALSE)
options(max.print=200)

```
LOAD LIBRARIES
```{r}
suppressPackageStartupMessages({
  library(dplyr)
library(Seurat)
library(hdf5r)
library(ggplot2)
library(harmony)
library(glmnet)
library(patchwork)
library(tidyr)
library(presto)
 library(scCustomize)
  library(reshape2)
  library(knitr)})

```
INPUT
```{r, eval = FALSE}
whole_me_tissue <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161373_wholeME_MEtissue_filtered_feature_bc_matrix.h5")
tissue_1 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161374_MEtissue1_filtered_feature_bc_matrix.h5")
tissue_2 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161375_MEtissue2_filtered_feature_bc_matrix.h5")
tissue_3 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161376_MEtissue3_filtered_feature_bc_matrix.h5")
tissue_4 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161377_MEtissue4_filtered_feature_bc_matrix.h5")
tissue_5 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161378_MEtissue5_filtered_feature_bc_matrix.h5")
tissue_6 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161379_MEtissue6_filtered_feature_bc_matrix.h5")
tissue_7 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161380_MEtissue7_filtered_feature_bc_matrix.h5")
whole_me_1 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161381_wholeME2_filtered_feature_bc_matrix.h5")
whole_me_2 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161382_wholeME3_filtered_feature_bc_matrix.h5")
whole_me_3 <- Read10X_h5("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_RAW/GSM6161383_wholeME1_filtered_feature_bc_matrix.h5")

```
Create seurat objects
```{r, eval = FALSE}
whole_me_tissue_so <- CreateSeuratObject(counts = whole_me_tissue, project = "whole_me", min.cells = 3)
tissue_1_so <- CreateSeuratObject(counts = tissue_1, project = "tissue_1", min.cells = 3)
tissue_2_so <- CreateSeuratObject(counts = tissue_2, project = "tissue_2", min.cells = 3)
tissue_3_so <- CreateSeuratObject(counts = tissue_3, project = "tissue_3", min.cells = 3)
tissue_4_so <- CreateSeuratObject(counts = tissue_4, project = "tissue_4", min.cells = 3)
tissue_5_so <- CreateSeuratObject(counts = tissue_5, project = "tissue_5", min.cells = 3)
tissue_6_so <- CreateSeuratObject(counts = tissue_6, project = "tissue_6", min.cells = 3)
tissue_7_so <- CreateSeuratObject(counts = tissue_7, project = "tissue_7", min.cells = 3)
whole_me_1_so <- CreateSeuratObject(counts = whole_me_1, project = "whole_me_1", min.cells = 3)
whole_me_2_so <- CreateSeuratObject(counts = whole_me_2, project = "whole_me_2", min.cells = 3)
whole_me_3_so <- CreateSeuratObject(counts = whole_me_3, project = "whole_me_3", min.cells = 3)
```
```{r}
whole_me_tissue_so[["percent.mt"]] <- PercentageFeatureSet(whole_me_tissue_so, pattern = "^MT-")
tissue_1_so[["percent.mt"]] <- PercentageFeatureSet(tissue_1_so, pattern = "^MT-")
tissue_2_so[["percent.mt"]] <- PercentageFeatureSet(tissue_2_so, pattern = "^MT-")
tissue_3_so[["percent.mt"]] <- PercentageFeatureSet(tissue_3_so, pattern = "^MT-")
tissue_4_so[["percent.mt"]] <- PercentageFeatureSet(tissue_4_so, pattern = "^MT-")
tissue_5_so[["percent.mt"]] <- PercentageFeatureSet(tissue_5_so, pattern = "^MT-")
tissue_6_so[["percent.mt"]] <- PercentageFeatureSet(tissue_6_so, pattern = "^MT-")
tissue_7_so[["percent.mt"]] <- PercentageFeatureSet(tissue_7_so, pattern = "^MT-")
whole_me_1_so[["percent.mt"]] <- PercentageFeatureSet(whole_me_1_so, pattern = "^MT-")
whole_me_2_so[["percent.mt"]] <- PercentageFeatureSet(whole_me_2_so, pattern = "^MT-")
whole_me_3_so[["percent.mt"]] <- PercentageFeatureSet(whole_me_3_so, pattern = "^MT-")

whole_me_tissue_so <- subset(whole_me_tissue_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10)
tissue_1_so <- subset(tissue_1_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_1_so) > 500)
tissue_2_so <- subset(tissue_2_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_2_so) > 500)
tissue_3_so <- subset(tissue_3_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_3_so) > 500)
tissue_4_so <- subset(tissue_4_so , subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_4_so) > 500)
tissue_5_so <- subset(tissue_5_so , subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_5_so) > 500)
tissue_6_so <- subset(tissue_6_so , subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_6_so) > 500)
tissue_7_so <- subset(tissue_7_so , subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10 & ncol(tissue_7_so) > 500)
whole_me_1_so <- subset(whole_me_1_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10)
whole_me_2_so <- subset(whole_me_2_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10)
whole_me_3_so <- subset(whole_me_3_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10)


```
Merge the seurat objects
```{r, eval = FALSE}
combined <- merge(
  x = whole_me_tissue_so,
  y = list(
    tissue_1_so, tissue_2_so, tissue_3_so, tissue_4_so, tissue_5_so,
    tissue_6_so, tissue_7_so, whole_me_1_so, whole_me_2_so, whole_me_3_so
  ),
  add.cell.ids = c(
    "whole_me_tissue", "tissue_1", "tissue_2", "tissue_3", "tissue_4", "tissue_5",
    "tissue_6", "tissue_7", "whole_me_1", "whole_me_2", "whole_me_3"
  )
)

# Join all the layers
combined_so <- JoinLayers(combined)

#saveRDS(combined, file = "/Users/pooja/Documents/Thesis/scRNA_Seurat/menstrual_blood/menstrual_effluent_data.rds")
colnames(combined_so) <- gsub("^.*_", "", colnames(combined_so))

# Ensure that the row names in the metadata are the barcodes
rownames(combined_so@meta.data) <- colnames(combined_so)

# If you want to keep barcodes as a column in meta.data (optional)
combined_so$barcode <- colnames(combined_so)

```
```{r, eval = FALSE}

combined_so[["percent.mt"]] <- PercentageFeatureSet(combined_so, pattern = "^MT-")

before_v_plot <- VlnPlot(combined_so, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)

before_v_plot + plot_annotation(title = "Before filtering")

# Filtering
me.data <- subset(combined_so, subset = nCount_RNA > 500 & nCount_RNA < 50000 & nFeature_RNA < 6000 & percent.mt < 10)

after_v_plot <- VlnPlot(me.data, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)

after_v_plot + plot_annotation(title = "After filtering")

# Each sample has to have at least 500 cells
samples_to_keep <- WhichCells(me.data, idents = Idents(me.data), downsample = 500)
subset.me <- subset(me.data, cells = samples_to_keep)
```


```{r}
# Normalise the data
options(future.globals.maxSize = 1000 * 1024^3)
me.data <- SCTransform(combined_so, vars.to.regress = "percent.mt", verbose = TRUE)
#saveRDS(me.data, file = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_normalised.rds")

me.data <- RunPCA(me.data, verbose = TRUE)

# Run harmony to correct for batch effects
me.data <- RunHarmony(me.data, group.by.vars = "orig.ident")

# Find neighbors and clusters
me.data <- FindNeighbors(me.data, dims = 1:10)
me.data <- FindClusters(me.data, resolution = 0.5)

# PLot UMAP
me.data <- RunUMAP(me.data, dims = 1:10)

head(me.data@meta.data)

umap <- DimPlot(me.data, reduction = "umap", label = TRUE)
ggsave(filename = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/umap.png", plot = umap)
saveRDS(me.data, file = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_unsub.rds")
```
Normalisation and scaling
```{r, eval = FALSE}
# Normalise the data
options(future.globals.maxSize = 1000 * 1024^3)
me.data <- SCTransform(me.data, vars.to.regress = "percent.mt", verbose = TRUE)
#saveRDS(me.data, file = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_normalised.rds")

me.data <- RunPCA(me.data, verbose = TRUE)

# Run harmony to correct for batch effects
me.data <- RunHarmony(me.data, group.by.vars = "orig.ident")

# Find neighbors and clusters
me.data <- FindNeighbors(me.data, dims = 1:10)
me.data <- FindClusters(me.data, resolution = 0.5)

# PLot UMAP
me.data <- RunUMAP(me.data, dims = 1:10)

head(me.data@meta.data)

umap <- DimPlot(me.data, reduction = "umap", label = TRUE)
ggsave(filename = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/umap.png", plot = umap)
saveRDS(me.data, file = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_unsub.rds")
```
```{r}
me.data <- readRDS("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_unsub.rds")
# Create the metadata data frame
metadata <- data.frame(
  library_name = c("wholeME_MEtissue", "wholeME_MEtissue", "wholeME_MEtissue", "MEtissue1", "MEtissue1", "MEtissue1", "MEtissue2", "MEtissue2", "MEtissue2", "MEtissue2",
                   "MEtissue3", "MEtissue3", "MEtissue3", "MEtissue4", "MEtissue5", "MEtissue5", "MEtissue6", "MEtissue7",
                   "wholeME2", "wholeME2", "wholeME2", "wholeME2", "wholeME2", "wholeME3", "wholeME3", "wholeME3", "wholeME3",
                   "wholeME3", "wholeME3", "wholeME1", "wholeME1", "wholeME1", "wholeME1", "wholeME1"),
  sample = c("Sample 1", "Sample 2", "Sample 3", "Sample 4", "Sample 5", "Sample 6", "Sample 7", "Sample 8", "Sample 9", "Sample 10", "Sample 11",
             "Sample 12", "Sample 13", "Sample 14", "Sample 15", "Sample 16", "Sample 17", "Sample 18", "Sample 19", "Sample 20",
             "Sample 21", "Sample 22", "Sample 23", "Sample 24", "Sample 25", "Sample 26", "Sample 27", "Sample 28", "Sample 29",
             "Sample 30", "Sample 31", "Sample 32", "Sample 33", "Sample 34")
)

# View the metadata
#head(metadata)
me.data$library_name <- metadata$library_name
me.data$sample <- metadata$sample

#head(me.data@meta.data)

sample_counts <- table(me.data$sample)

sample_counts_df <- as.data.frame(sample_counts)

colnames(sample_counts_df) <- c("Sample", "Number_of_Cells")

# View the table
print(sample_counts_df)

print(paste("The total num of orig.ident = ", (length(unique(me.data@meta.data$orig.ident)))))
```
```{r}
# Load the metadata file
meta_data <- read.table("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/GSE203191_Shih_endo_meta_frame.tsv", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

prefix_mapping <- c(
  "wholeME_MEtissue" = "whole_me_tissue",
  "MEtissue1" = "tissue_1",
  "MEtissue2" = "tissue_2",
  "MEtissue3" = "tissue_3",
  "MEtissue4" = "tissue_4",
  "MEtissue5" = "tissue_5",
  "MEtissue6" = "tissue_6",
  "MEtissue7" = "tissue_7",
  "wholeME1" = "whole_me_1",
  "wholeME2" = "whole_me_2",
  "wholeME3" = "whole_me_3"
)

# Add a new column with the prefixes based on the run column
meta_data$prefix <- prefix_mapping[meta_data$run]

# Combine the prefix and barcode columns to create the new barcode names
meta_data$barcode <- paste(meta_data$prefix, meta_data$barcode, sep = "_")


me_data_df <- as.data.frame(combined_so@meta.data)
me_data_df$barcode <- rownames(me_data_df)

# Add barcode as a column to the me_data_df
#me_data_df$barcode <- me_data_barcodes$barcode

# Perform the left join with meta_data
merged_data <- left_join(me_data_df, meta_data, by = "barcode")
rownames(merged_data) <- merged_data$barcode
combined_so@meta.data <- merged_data
```
```{r}

before_v_plot <- VlnPlot(combined_so, features = c("nFeature_RNA", "nCount_RNA", "percent.mt.x"),ncol = 3, pt.size = 0)

me.data@meta.data$clusterID_status <- ifelse(is.na(me.data@meta.data$clusterID), "NA", "Present")

# Now, generate the violin plot, coloring by this new column
before_v_plot <- VlnPlot(
  me.data,
  features = c("nFeature_RNA", "nCount_RNA", "percent.mt.x"),
  ncol = 3,
  pt.size = 0,
  group.by = "clusterID_status",
  cols = c("gray", "blue")
)

```
```{r}
set.seed(123)
#me.data <- readRDS("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/me_unsub.rds")
#DefaultAssay(me.data) <- "SCT"
all_markers <- FindAllMarkers(me.data, only.pos = TRUE) #min.pct = 0.25, logfc.threshold = 0.25 if needed

all_marker <- all_markers %>%
         group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 20) %>%
    ungroup() -> top10

Uterine_natural_killer_cells = c("CD45", "PTPRC", "CD56", "NCAM1")
Stromal_cells = c("CD73", "NT5E", "CD90", "Thy1", "CD105", "ENG")
CD4p_Tcells =  c("CD3D", "CD3E", "CD4")
Myeloid_cells = c("CD14","CD45", "PTPRC")
Epithelial_cells = c("CD326", "EPCAM")
CD8p_Tcells = c("CD8A", "CD45", "PTPRC","CD3D", "CD3E")
B_cells = c("CD19", "MS4A1", "CD20", "CD45", "PTPRC")
Plasmacytoid_dendritic_cells = c("CD303", "CLEC4C", "CD85g", "LILRA4", "IL3RA", "PTPRC")
Endothelial_like_cells = c("CD31", "CD34", "CD105", "ENG", "CD45", "PTPRC")
Granulocytes = c("GCSAML", "CPA3")
Unkown = c("CD45", "PTPRC")

celltype.marker <- list(
        Uterine_natural_killer_cells = c("CD45", "PTPRC", "CD56", "NCAM1"),
        Stromal_cells = c("CD73", "NT5E", "CD90", "THY1", "CD105", "ENG"),
        CD4p_Tcells =  c("CD3D", "CD3E", "CD4", "PTPRC"),
        Myeloid_cells = c("CD14","CD45", "PTPRC"),
        Epithelial_cells =  c("CD326", "EPCAM"),
        CD8p_Tcells = c("CD8A", "CD45", "PTPRC","CD3D", "CD3E"),
        B_cells = c("CD19", "MS4A1", "CD20", "CD45", "PTPRC"),
        Plasmacytoid_dendritic_cells = c("CD303", "CLEC4C", "CD85g", "LILRA4", "IL3RA", "PTPRC"),
        Endothelial_like_cells = c("CD31", "CD34", "CD105", "ENG", "CD45", "PTPRC"),
        Granulocytes = c("GCSAML", "CPA3"),
        Unkown = c("CD45", "PTPRC"))

gene.markers <- c("CD45", "PTPRC", "CD56", "NCAM1", "CD73" , "NT5E", "CD90", "THY1", "CD105", "ENG",
               "CD3D", "CD3E", "CD4", "CD14", "CD326", "EPCAM", "CD8A", "CD19", "MS4A1",
               "CD123", "IL3RA", "CD303" ,"CLEC4C", "CD85g", "LILRA4", "CD31", "CD34",
               "GCSAML", "CPA3")

cell_type_plot <- function(obj, cell_markers) {
  for (cell_type in names(cell_markers)) {
    markers <- cell_markers[[cell_type]]
    #print(markers)
    markers_found <- intersect(markers,rownames(me.data@assays$SCT@scale.data))
    #print(markers_found)
    # Skip if no markers are found
    if (length(markers_found) == 0) {
      cat("No markers found for", cell_type, "- skipping.\n")
      next
    }
    # Generate and save VlnPlot
    vln_plot <- VlnPlot(obj, features = markers, slot = "counts", log = TRUE)
    #ggsave(filename = paste0("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/figures/vln_", cell_type, ".png"), plot = vln_plot)

    # Generate and save FeaturePlot
    feature_plot <- FeaturePlot(obj, features = markers)
    #ggsave(filename = paste0("/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/figures/feature_", cell_type, ".png"), plot = feature_plot)
  }
}

cell_type_plot(obj = me.data, cell_markers = celltype.marker)

#ggsave(filename = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/featureplot2.png", plot = feature.plot)
dot.plot <- DotPlot(object =me.data, features = gene.markers)
#ggsave(filename = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/dot_plot.png", plot = dot.plot)
#heatmap.plot <- DoHeatmap(me.data, features = gene.markers, size = 3) + NoLegend()
#ggsave(filename = "/home/inf-21-2023/thesis/ME_scRNA/menstrual_blood/heatmap_features.png", plot = heatmap.plot)


```
```{r}

new.clusterids= c("Granulocytes", "CD4 positive", "Myeloid1", "Myeloid2", "uNK 1 cells", "Stromal cells 1", "CD8 T1", "Epithelial cells", "CD8 T2",
                         "CD8 T4", "B cells", "Stromal 2 cells", "Myeloid3", "CD8 T3", "Plasmocytoid dendritic cells", "Unknown1", "uNK 2 cells", "Unknown2")
names(new.clusterids) <- levels(me.data)
me.data <- RenameIdents(me.data, new.clusterids)
DimPlot(me.data, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```
```{r}
table(Idents(me.data))

#me.data <- SetIdent(me.data, value = "subject")

receptor_genes <- c("^ESR1$", "^ESR2$", "^NR3C1$", "^NR3C2$", "^PGR", "^AR$", "^GPER", "^LGR1", "^FSHR", "^LHR", "^LCGR",
"^LGR2", "^ULG5", "^GNRH", "^LHRH", "^GRH$")

# Extract all genes from the Seurat object
all_genes <- rownames(me.data)

filtered_genes <- grep(paste(receptor_genes, collapse = "|"), all_genes, value = TRUE)

# Calculate average expression of receptor genes across cell types
receptor_expression <- AverageExpression(me.data, assay = "SCT", return.seurat = TRUE)

DoHeatmap(receptor_expression, features = filtered_genes, size = 2, draw.lines = FALSE)
#h2 <- DoHeatmap(receptor_expression_2, features = filtered_genes, size = 2, draw.lines = FALSE)

```
```{r}
percent_stats <- Percent_Expressing(seurat_object = me.data, features = filtered_genes, threshold = 0, group_by = "sample")


cell_types_order <- c("Granulocytes", "Myeloid1", "Myeloid2", "Myeloid3",
  "CD4 positive", "CD8 T1", "CD8 T2", "CD8 T3", "CD8 T4",
  "uNK 1 cells", "uNK 2 cells",
  "Plasmocytoid dendritic cells",
  "B cells",
  "Stromal cells 1", "Stromal 2 cells",
  "Epithelial cells",
  "Unknown1", "Unknown2")

receptors_order <- c("ESR1", "ESR2", "NR3C1", "NR3C2", "PGR", "PGRMC1", "PGRMC2", "AR", "GPER1")


plot_data <- DotPlot(me.data,
                     features = receptors_order)

plot_data$data$id <- factor(plot_data$data$id,
                           levels = cell_types_order)

#
plot <- plot_data + coord_flip() + theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(plot, filename = "me_percent_exp.pdf")
```
```{r}
sessionInfo()
```
